repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: cookiecutter_template/
        args:
          - --line-length=120

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: cookiecutter_template/
        args: ["--profile", "black"]

  - repo: https://github.com/crate-ci/typos
    rev: v1.16.12
    hooks:
      - id: typos

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        exclude: .*\.(json|html|raw|ipynb|js|md|htm)

  - repo: https://github.com/pycqa/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier

  - repo: https://github.com/sourcery-ai/sourcery
    rev: v1.9.0
    hooks:
      - id: sourcery
        args: [--diff=git diff HEAD, --no-summary, --fix]
