repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: cookiecutter_template/
        args:
          - --line-length=120

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: cookiecutter_template/
        args: [ "--profile", "black" ]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        exclude: .*\.(json|html|raw|ipynb|js|md|htm)

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v1.4.1'
#    hooks:
#      - id: mypy
#        args: [ "--ignore-imports" ]
